#INTRO
#Set up is quick and easy. Simply replace any example text with your nonprofit's information.
#To leave a field blank, simply remove everything after the colon (:) or place a hashtag (#) at the start of the line.
#If you see '> # Enter on the next line', be sure the next line remains indented two spaces.

#REQUIRED
org_name: Charlotte's Army
org_summary: > # Enter your summary on the next line. Be sure to indent by two spaces.
  A non-profit organization with the goal of providing aid and support to families with babies in the neonatal intensive care unit (NICU).
org_full_description: > # Enter your description on the next line. Be sure to indent by two spaces.
  This organization was founded in memory of Charlotte Marie Kocsis by her loving parents Christian and Maddy Kocsis. Charlotte was born prematrurely due to severe pre-eclampsia and passed away after nearly a month in the NICU. During this time, she was loved by and inspired not only her parents, but her entire family and all of the staff that handled her care. Charlotte was the strongest fighter that we had ever seen and we know that there are many more babies like this that need support. We would like to provide aid and support in any way that we can including gift baskets for the families, a listening ear, and financial assistance. We hope that with your support, we may help some of those families and babies fighting to get better.

#OPTIONAL
#Non US-address support coming soon
org_general_email_inbox: charlottesarmy@outlook.com
org_street_address:  #Please include suite number on the line below
org_address_suite: 
org_city: Saint Augustine
org_state: FL
org_zip: > # Enter zip on next line. Be sure to indent by two spaces.
  32084
org_phone: > # Enter phone on next line. Be sure to indent by two spaces.
  (904) 401-4233

#SOCIAL MEDIA
org_twitter_username: charlottesarmy
org_facebook_username: charlottesarmy
org_instagram_username: charlottesarmy

#TAX STATUS
#Your site will display an appropriate message below the Donate section
#If your organization is fiscally sponsored, enter true below and add your sponsor's name. Otherwise enter false.
fiscal_sponsor: false
fiscal_sponsor_name:
#If your organization is currently registered as a 501(c)3 organization, enter true below. Otherwise enter false. Enter false if you have a fiscal sponsor.
is_501c3: true

#ONLINE DONATIONS & EMAIL SIGNUPS
#To use these services, enter the required usernames. For further instructions, consult the README file.
#If you do not wish to use a service, simply remove everything after the colon (:), leaving the item blank
donorbox_campaign_name: free-template-demo
tinyletter_username: interestingnonprofits

#SEARCH ENGINES
#Changing this next setting to 'true' will allow your site to be indexed by search engines (like Google)
publish: false

#COLOR SCHEME
#Select one of the five color schemes (default, one, two, three, or four)
color_scheme: two

# *** DO NOT CHANGE ANYTHING BELOW THIS LINE ***

# Unless you know what you're doing, no need to change anything below
# Build settings
baseurl: "" # the subpath of your site, e.g. /blog/
markdown: kramdown
kramdown:
  input: GFM

sass:
    sass_dir: assets/_sass
    style: compressed

#Features under development
#These are not yet fully supported, but should give you a head start if you know what you're doing
paypal_button_id: #Not yet available
smartergiving_id: #Not yet available
#mailchimp_embed_code: > # Enter Mailchimp post url on next line.
#  //getkyn.us5.list-manage.com/subscribe/post?u=1407d7ee4cd0d47986cd54315&amp;id=cdc32b64fe
#mailchimp_spam_guard: b_753395b9f963c9ea2d6980b7c_9e1559c2f0
